### ISSUE TITLE
"pearl init" fails on Arch Linux

### ISSUE THREAD

**Issue by Snogard** [pearl-core/pearl#103]
Error: 

```
* Setting up $PEARL_HOME directory as /home/test/.local/share/pearl
* Activated Pearl for Bash
Traceback (most recent call last):
  File "/usr/bin/pearl", line 13, in <module>
    main()
  File "/usr/bin/pearl", line 9, in main
    pearl(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/pearllib/pearl.py", line 100, in pearl
    _pearl(pearl_env, args)
  File "/usr/lib/python3.9/site-packages/pearllib/pearl.py", line 55, in _pearl
    syst.init_pearl(pearl_env, args)
  File "/usr/lib/python3.9/site-packages/pearllib/system.py", line 49, in init_pearl
    apply(
  File "/usr/lib/python3.9/site-packages/pearllib/utils.py", line 163, in apply
    content = f.read()
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 10084: invalid start byte

```

My locale:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES=
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

If you need more info just ask ;)

**Comment by Snogard** [comment]
works with latest version
